# Build the x86 hook DLL + loader (the game and mss32.dll are 32-bit).
# Emits hook.dll + berkutx_loader.exe into $OutDir (default: this folder).
# Cross-platform paths (Join-Path) so it runs on Windows and on the Linux CI.
param([string]$OutDir = $PSScriptRoot)
$ErrorActionPreference = 'Stop'
$gxx = 'i686-w64-mingw32-g++'
Push-Location $PSScriptRoot
try {
    New-Item -ItemType Directory -Force -Path $OutDir | Out-Null

    # Embed the fake-template stub: template.lua -> template_lua.h (byte array).
    $bytes = [IO.File]::ReadAllBytes((Join-Path $PSScriptRoot 'template.lua'))
    $sb = [Text.StringBuilder]::new()
    [void]$sb.AppendLine("// generated by build.ps1 from template.lua — do not edit")
    [void]$sb.AppendLine("static const unsigned char TEMPLATE_LUA[] = {")
    for ($i = 0; $i -lt $bytes.Length; $i += 16) {
        $chunk = $bytes[$i..([Math]::Min($i + 15, $bytes.Length - 1))]
        [void]$sb.AppendLine('    ' + (($chunk | ForEach-Object { '0x{0:x2}' -f $_ }) -join ', ') + ',')
    }
    [void]$sb.AppendLine("};")
    [void]$sb.AppendLine("static const unsigned TEMPLATE_LUA_LEN = $($bytes.Length);")
    [IO.File]::WriteAllText((Join-Path $PSScriptRoot 'template_lua.h'), $sb.ToString())

    $dll = Join-Path $OutDir 'hook.dll'
    $exe = Join-Path $OutDir 'berkutx_loader.exe'
    & $gxx -shared -O2 -s -static -o $dll hook.cpp -lkernel32
    & $gxx -O2 -s -static -municode -o $exe berkutx_loader.cpp
    Write-Host ("hook.dll            {0,7} bytes" -f (Get-Item $dll).Length)
    Write-Host ("berkutx_loader.exe  {0,7} bytes" -f (Get-Item $exe).Length)
} finally { Pop-Location }
