# Build the self-contained x86 loader: compile hook.dll, embed it + berkutx_rng.exe as RCDATA
# resources, and link berkutx_loader.exe — the single file that gets shipped. The loader unpacks
# the payload at runtime. Cross-platform paths (Join-Path) so it runs on Windows and on the Linux CI.
param(
    [string]$OutDir = $PSScriptRoot,
    [string]$RngExe                       # pre-built berkutx_rng.exe to embed (built by the top-level build.ps1)
)
$ErrorActionPreference = 'Stop'
$gxx     = 'i686-w64-mingw32-g++'
# windres MUST match g++'s target (32-bit pe-i386). Prefer the prefixed cross tool (apt CI), then the
# windres sitting next to g++ (msys2 mingw32 layout), and only then a bare `windres` on PATH — on msys2 a
# bare windres resolves to /usr/bin/windres, whose object the 32-bit linker rejects ("file format not
# recognized").
$gxxCmd  = Get-Command $gxx -ErrorAction SilentlyContinue
$gxxDir  = if ($gxxCmd) { Split-Path $gxxCmd.Source } else { $null }
$windres = (Get-Command 'i686-w64-mingw32-windres' -ErrorAction SilentlyContinue).Source
if (-not $windres -and $gxxDir) {
    $sib = Join-Path $gxxDir 'windres.exe'
    if (Test-Path $sib) { $windres = $sib }
}
if (-not $windres) { $windres = (Get-Command 'windres' -ErrorAction SilentlyContinue).Source }
if (-not $windres) { throw "windres not found (need i686-w64-mingw32-windres, windres next to g++, or windres on PATH)" }
Push-Location $PSScriptRoot
try {
    New-Item -ItemType Directory -Force -Path $OutDir | Out-Null
    $stage = Join-Path $PSScriptRoot '_build'
    New-Item -ItemType Directory -Force -Path $stage | Out-Null

    # Embed the fake-template stub: template.lua -> template_lua.h (byte array).
    $bytes = [IO.File]::ReadAllBytes((Join-Path $PSScriptRoot 'template.lua'))
    $sb = [Text.StringBuilder]::new()
    [void]$sb.AppendLine("// generated by build.ps1 from template.lua — do not edit")
    [void]$sb.AppendLine("static const unsigned char TEMPLATE_LUA[] = {")
    for ($i = 0; $i -lt $bytes.Length; $i += 16) {
        $chunk = $bytes[$i..([Math]::Min($i + 15, $bytes.Length - 1))]
        [void]$sb.AppendLine('    ' + (($chunk | ForEach-Object { '0x{0:x2}' -f $_ }) -join ', ') + ',')
    }
    [void]$sb.AppendLine("};")
    [void]$sb.AppendLine("static const unsigned TEMPLATE_LUA_LEN = $($bytes.Length);")
    [IO.File]::WriteAllText((Join-Path $PSScriptRoot 'template_lua.h'), $sb.ToString())

    # 1) hook.dll — embedded in the loader, not shipped on its own
    $hookDll = Join-Path $stage 'hook.dll'
    & $gxx -shared -O2 -s -static -o $hookDll hook.cpp -lkernel32
    if ($LASTEXITCODE -ne 0) { throw "hook.dll build failed ($LASTEXITCODE)" }

    # 2) the re-roller to embed
    if (-not $RngExe) { $RngExe = Join-Path $OutDir 'berkutx_rng.exe' }
    if (-not (Test-Path $RngExe)) { throw "berkutx_rng.exe not found at '$RngExe' — build the reroller first (use the top-level build.ps1)" }
    $RngExe = (Resolve-Path $RngExe).Path

    # 3) resources.rc -> resources.o  (forward slashes for the windres preprocessor)
    $rc = "HOOKDLL RCDATA `"$($hookDll -replace '\\','/')`"`nRNGEXE RCDATA `"$($RngExe -replace '\\','/')`"`n"
    $rcPath = Join-Path $stage 'resources.rc'
    $resObj = Join-Path $stage 'resources.o'
    [IO.File]::WriteAllText($rcPath, $rc)
    & $windres -i $rcPath -o $resObj
    if ($LASTEXITCODE -ne 0) { throw "windres failed ($LASTEXITCODE)" }

    # 4) link the self-contained loader (the single shipped file)
    $exe = Join-Path $OutDir 'berkutx_loader.exe'
    & $gxx -O2 -s -static -municode -o $exe berkutx_loader.cpp $resObj
    if ($LASTEXITCODE -ne 0) { throw "berkutx_loader.exe build failed ($LASTEXITCODE)" }
    Write-Host ("berkutx_loader.exe  {0,9} bytes  (embeds hook.dll {1} b + berkutx_rng.exe {2} b)" -f `
        (Get-Item $exe).Length, (Get-Item $hookDll).Length, (Get-Item $RngExe).Length)
} finally { Pop-Location }
